name: blog_wave
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  supabase_flutter: ^2.5.2
  dotted_border: ^2.1.0
  smooth_page_indicator: ^1.0.0
  image_picker: ^1.1.1
  uuid: ^4.4.0
  lordicon: ^1.0.3
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.3.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  shared_preferences: ^2.2.3 
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/doc.json
    - assets/images/
